In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
calendar_file = "calendar.csv"
calendar_df = pd.read_csv(calendar_file)
calendar_df.head()

   listing_id        date available price
0    12147973  2017-09-05         f   NaN
1    12147973  2017-09-04         f   NaN
2    12147973  2017-09-03         f   NaN
3    12147973  2017-09-02         f   NaN
4    12147973  2017-09-01         f   NaN

In [3]:
# convert to boolean
calendar_df["available"].replace(["t","f"], [True,False], inplace=True)

In [4]:
# remove dollar sign
calendar_df["price"] = calendar_df["price"].replace({'\$': '', ',': ''}, regex=True)
# convert the price column to numeric values 
calendar_df["price"] = pd.to_numeric(calendar_df["price"])
calendar_df.head()

   listing_id        date  available  price
0    12147973  2017-09-05      False    NaN
1    12147973  2017-09-04      False    NaN
2    12147973  2017-09-03      False    NaN
3    12147973  2017-09-02      False    NaN
4    12147973  2017-09-01      False    NaN

In [5]:
listings_file = "listings.csv"
listings_df = pd.read_csv(listings_file)
listings_df.head()

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,...,review_scores_value,requires_license,license,jurisdiction_names,instant_bookable,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,reviews_per_month
0,12147973,https://www.airbnb.com/rooms/12147973,20160906204935,2016-09-07,Sunny Bungalow in the City,"Cozy, sunny, family home. Master bedroom high...",The house has an open and cozy feel at the sam...,"Cozy, sunny, family home. Master bedroom high...",none,"Roslindale is quiet, convenient and friendly. ...",...,NaN,f,NaN,NaN,f,moderate,f,f,1,NaN
1,3075044,https://www.airbnb.com/rooms/3075044,20160906204935,2016-09-07,Charming room in pet friendly apt,Charming and quiet room in a second floor 1910...,Small but cozy and quite room with a full size...,Charming and quiet room in a second floor 1910...,none,"The room is in Roslindale, a diverse and prima...",...,9.0,f,NaN,NaN,t,moderate,f,f,1,1.30
2,6976,https://www.airbnb.com/rooms/6976,20160906204935,2016-09-07,Mexican Folk Art Haven in Boston,"Come stay with a friendly, middle-aged guy in ...","Come stay with a friendly, middle-aged guy in ...","Come stay with a friendly, middle-aged guy in ...",none,The LOCATION: Roslindale is a safe and diverse...,...,10.0,f,NaN,NaN,f,moderate,t,f,1,0.47
3,1436513,https://www.airbnb.com/rooms/1436513,20160906204935,2016-09-07,Spacious Sunny Bedroom Suite in Historic Home,Come experience the comforts of home away from...,Most places you find in Boston are small howev...,Come experience the comforts of home away from...,none,Roslindale is a lovely little neighborhood loc...,...,10.0,f,NaN,NaN,f,moderate,f,f,1,1.00
4,7651065,https://www.airbnb.com/rooms/7651065,20160906204935,2016-09-07,Come Home to Boston,"My comfy, clean and relaxing home is one block...","Clean, attractive, private room, one block fro...","My comfy, clean and relaxing home is one block...",none,"I love the proximity to downtown, the neighbor...",...,10.0,f,NaN,NaN,f,flexible,f,f,1,2.25

In [6]:
reviews_file = "reviews.csv"
reviews_df = pd.read_csv(reviews_file)
reviews_df.head()

,listing_id,id,date,reviewer_id,reviewer_name,comments
0,1178162,4724140,2013-05-21,4298113,Olivier,My stay at islam's place was really cool! Good...
1,1178162,4869189,2013-05-29,6452964,Charlotte,Great location for both airport and city - gre...
2,1178162,5003196,2013-06-06,6449554,Sebastian,We really enjoyed our stay at Islams house. Fr...
3,1178162,5150351,2013-06-15,2215611,Marine,The room was nice and clean and so were the co...
4,1178162,5171140,2013-06-16,6848427,Andrew,Great location. Just 5 mins walk from the Airp...

In [7]:
#merge listings and calendar
listings_calendar_df = listings_df.merge(calendar_df, left_on='id', right_on='listing_id')

#sanity check
listings_calendar_df.head()

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,...,instant_bookable,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,reviews_per_month,listing_id,date,available,price_y
0,12147973,https://www.airbnb.com/rooms/12147973,20160906204935,2016-09-07,Sunny Bungalow in the City,"Cozy, sunny, family home. Master bedroom high...",The house has an open and cozy feel at the sam...,"Cozy, sunny, family home. Master bedroom high...",none,"Roslindale is quiet, convenient and friendly. ...",...,f,moderate,f,f,1,NaN,12147973,2017-09-05,False,NaN
1,12147973,https://www.airbnb.com/rooms/12147973,20160906204935,2016-09-07,Sunny Bungalow in the City,"Cozy, sunny, family home. Master bedroom high...",The house has an open and cozy feel at the sam...,"Cozy, sunny, family home. Master bedroom high...",none,"Roslindale is quiet, convenient and friendly. ...",...,f,moderate,f,f,1,NaN,12147973,2017-09-04,False,NaN
2,12147973,https://www.airbnb.com/rooms/12147973,20160906204935,2016-09-07,Sunny Bungalow in the City,"Cozy, sunny, family home. Master bedroom high...",The house has an open and cozy feel at the sam...,"Cozy, sunny, family home. Master bedroom high...",none,"Roslindale is quiet, convenient and friendly. ...",...,f,moderate,f,f,1,NaN,12147973,2017-09-03,False,NaN
3,12147973,https://www.airbnb.com/rooms/12147973,20160906204935,2016-09-07,Sunny Bungalow in the City,"Cozy, sunny, family home. Master bedroom high...",The house has an open and cozy feel at the sam...,"Cozy, sunny, family home. Master bedroom high...",none,"Roslindale is quiet, convenient and friendly. ...",...,f,moderate,f,f,1,NaN,12147973,2017-09-02,False,NaN
4,12147973,https://www.airbnb.com/rooms/12147973,20160906204935,2016-09-07,Sunny Bungalow in the City,"Cozy, sunny, family home. Master bedroom high...",The house has an open and cozy feel at the sam...,"Cozy, sunny, family home. Master bedroom high...",none,"Roslindale is quiet, convenient and friendly. ...",...,f,moderate,f,f,1,NaN,12147973,2017-09-01,False,NaN

In [8]:
#choose only the necessary columns
cleaned_df = listings_calendar_df[["id", "listing_url", "name", "price_y", "number_of_reviews", "review_scores_rating", "date", "available"]]

#sanity check
cleaned_df.head()

,id,listing_url,name,price_y,number_of_reviews,review_scores_rating,date,available
0,12147973,https://www.airbnb.com/rooms/12147973,Sunny Bungalow in the City,NaN,0,NaN,2017-09-05,False
1,12147973,https://www.airbnb.com/rooms/12147973,Sunny Bungalow in the City,NaN,0,NaN,2017-09-04,False
2,12147973,https://www.airbnb.com/rooms/12147973,Sunny Bungalow in the City,NaN,0,NaN,2017-09-03,False
3,12147973,https://www.airbnb.com/rooms/12147973,Sunny Bungalow in the City,NaN,0,NaN,2017-09-02,False
4,12147973,https://www.airbnb.com/rooms/12147973,Sunny Bungalow in the City,NaN,0,NaN,2017-09-01,False

In [9]:
#drop na's
dropped_listings_df = cleaned_df.dropna(how='any', axis=0)

#sanity check
dropped_listings_df

,id,listing_url,name,price_y,number_of_reviews,review_scores_rating,date,available
365,3075044,https://www.airbnb.com/rooms/3075044,Charming room in pet friendly apt,65.0,36,94.0,2017-08-22,True
366,3075044,https://www.airbnb.com/rooms/3075044,Charming room in pet friendly apt,65.0,36,94.0,2017-08-21,True
367,3075044,https://www.airbnb.com/rooms/3075044,Charming room in pet friendly apt,65.0,36,94.0,2017-08-20,True
368,3075044,https://www.airbnb.com/rooms/3075044,Charming room in pet friendly apt,75.0,36,94.0,2017-08-19,True
369,3075044,https://www.airbnb.com/rooms/3075044,Charming room in pet friendly apt,75.0,36,94.0,2017-08-18,True
...,...,...,...,...,...,...,...,...
1308518,14603878,https://www.airbnb.com/rooms/14603878,Great Location; Train and Restaurants,59.0,2,90.0,2016-09-12,True
1308519,14603878,https://www.airbnb.com/rooms/14603878,Great Location; Train and Restaurants,59.0,2,90.0,2016-09-11,True
1308520,14603878,https://www.airbnb.com/rooms/14603878,Great Location; Train and Restaurants,59.0,2,90.0,2016-09-10,True
1308521,14603878,https://www.airbnb.com/rooms/14603878,Great Location; Train and Restaurants,59.0,2,90.0,2016-09-09,True
1308522,14603878,https://www.airbnb.com/rooms/14603878,Great Location; Train and Restaurants,59.0,2,90.0,2016-09-08,True

In [10]:
#show only those with rating greater than 90

#index of rows with rating greater than 90
indexNames = dropped_listings_df[dropped_listings_df['review_scores_rating'] < 90.0].index


#drop the lisitngs with rating greater than 90
dropped_listings_df.drop(indexNames , inplace=True)

#sanity check
dropped_listings_df.head()

Data Entries: 365313

/Users/noetorres/opt/miniconda3/envs/PythonData/lib/python3.6/site-packages/pandas/core/frame.py:3997: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

,id,listing_url,name,price_y,number_of_reviews,review_scores_rating,date,available
365,3075044,https://www.airbnb.com/rooms/3075044,Charming room in pet friendly apt,65.0,36,94.0,2017-08-22,True
366,3075044,https://www.airbnb.com/rooms/3075044,Charming room in pet friendly apt,65.0,36,94.0,2017-08-21,True
367,3075044,https://www.airbnb.com/rooms/3075044,Charming room in pet friendly apt,65.0,36,94.0,2017-08-20,True
368,3075044,https://www.airbnb.com/rooms/3075044,Charming room in pet friendly apt,75.0,36,94.0,2017-08-19,True
369,3075044,https://www.airbnb.com/rooms/3075044,Charming room in pet friendly apt,75.0,36,94.0,2017-08-18,True

In [11]:
#drop by duplicate dates and keep the latest
dropped_listings_df.sort_values('date').drop_duplicates('id',keep='last')

,id,listing_url,name,price_y,number_of_reviews,review_scores_rating,date,available
438729,4410142,https://www.airbnb.com/rooms/4410142,Best Location in Boston (Copley Sq),200.0,18,92.0,2016-09-06,True
748249,9299923,https://www.airbnb.com/rooms/9299923,Beacon Hill 1BR near Downtown,259.0,14,94.0,2016-09-06,True
635829,2660908,https://www.airbnb.com/rooms/2660908,$99 Historic Charm Walk to Subway,99.0,15,95.0,2016-09-06,True
1116898,4435883,https://www.airbnb.com/rooms/4435883,Luxury Loft in Boston's Fort Point District,200.0,2,100.0,2016-09-07,True
942428,13265095,https://www.airbnb.com/rooms/13265095,Brighton 2BR by BC campus with lake view and AC,200.0,2,100.0,2016-09-07,True
...,...,...,...,...,...,...,...,...
1089418,1821633,https://www.airbnb.com/rooms/1821633,Queen Size Four Poster Bed,100.0,123,98.0,2017-09-05,True
603994,7984949,https://www.airbnb.com/rooms/7984949,"Private room, East Boston",89.0,6,93.0,2017-09-05,True
948270,11147761,https://www.airbnb.com/rooms/11147761,"Lovely 2BR+, 2BA w/ Exercise Room",194.0,13,98.0,2017-09-05,True
774009,14760739,https://www.airbnb.com/rooms/14760739,Single room in large apt Downtown — Room 2,80.0,1,100.0,2017-09-05,True
72514,554720,https://www.airbnb.com/rooms/554720,Boston Charm - Condo,240.0,108,95.0,2017-09-05,True

In [12]:
#create database connection
connection = "postgres:postgres@localhost:5432/airbnb_db"
engine = create_engine(f'postgresql://{connection}')

ModuleNotFoundError: No module named 'psycopg2'

In [ ]:
#table names
engine.table_names()

In [ ]:
#load df into database
calendar.to_sql(name='premise', con=engine, if_exists='append', index=True)

In [ ]:
listings.to_sql(name='county', con=engine, if_exists='append', index=True)

In [ ]:
reviews.to_sql(name='county', con=engine, if_exists='append', index=True)

In [ ]:
#query results to confirm data has been added
pd.read_sql_query('select * from calendar', con=engine).head()

In [ ]:
pd.read_sql_query('select * from listings', con=engine).head()

In [ ]:
pd.read_sql_query('select * from reviews', con=engine).head()